#!/usr/bin/ruby
# -*- coding: utf-8 -*-
#

require 'gyazz'

#wiki = Gyazz::Wiki.new('増井研')
#wiki.host = "http://Gyazz.com"
#wiki.auth = {:username => 'pitecan', :password => 'masu1lab'}

wiki = Gyazz::Wiki.new('推薦Wiki')

wiki.pages.each { |page|
  puts page.name
}
