#!/usr/bin/ruby
# -*- coding: utf-8 -*-
#

require 'gyazz'

module Gyazz
  class Wiki
    def get(path, query={})
      res = HTTParty.get "#{@host}#{path}", :query => query, :basic_auth => @basic_auth, :timeout => 1000000
      case res.code
      when 200
        return res.body
      else
        raise Gyazz::Error, res.body
      end
    end

    def post(path, opts)
      opts[:basic_auth] = @basic_auth if @basic_auth
      opts[:timeout] = 1000000

      res = HTTParty.post "#{@host}#{path}", opts
      case res.code
      when 200
        return res.body
      else
        raise Gyazz::Error, res.body
      end
    end
  end
end


#wiki = Gyazz::Wiki.new('増井研')
#wiki.host = "http://Gyazz.com"
#wiki.auth = {:username => 'pitecan', :password => 'masu1lab'}

wiki = Gyazz::Wiki.new('Gictionary')

wiki.pages.each { |page|
  puts page.name
}
